#!/bin/bash
./clearrootfs
./grfd.sh
./buildbusybox.sh
./installglibc
./installguile
./installgc
./installlibffi
./installlibunistring
./installlibgmp
./installlibcrypt
./installmake
./installopm
rm rootfs.sfs
mksquashfs rootfs rootfs.sfs -comp xz