#!/bin/bash
wget https://slackware.uk/slackware/slackware64-15.0/slackware64/d/make-4.3-x86_64-3.txz
sudo tar -xf make-4.3-x86_64-3.txz -C rootfs
rm make-4.3-x86_64-3.txz
#TODO:Fix "make: error while loading shared libraries: libgc.so.1: cannot open shared object file: No such file or directory"