#!/bin/bash
cd rootfs
wget 	https://vault.centos.org/centos/8/BaseOS/x86_64/os/Packages/glibc-2.28-164.el8.x86_64.rpm
sudo chroot ./ /bin/rpm -i glibc-2.28-164.el8.x86_64.rpm
rm glibc-2.28-164.el8.x86_64.rpm
cd ..
